### ISSUE TITLE
bundle exec bin/ami_proxy.rb bundler: failed to load command: bin/ami_proxy.rb (bin/ami_proxy.rb)

### ISSUE THREAD

**Issue by hkjarral** [thedonvaughn/queue-tip#2]
It fails at this command.

**Comment by hkjarral** [comment]
Here is full output

/queue-tip$ bundle exec bin/ami_proxy.rb
bundler: failed to load command: bin/ami_proxy.rb (bin/ami_proxy.rb)
NameError: undefined local variable or method `host' for main:Object
  bin/ami_proxy/config/asterisk.rb:5:in `<top (required)>'
  bin/ami_proxy.rb:30:in `load'
  bin/ami_proxy.rb:30:in `block in <top (required)>'
  bin/ami_proxy.rb:30:in `glob'
  bin/ami_proxy.rb:30:in `<top (required)>'

**Comment by hkjarral** [comment]
NVM the ":" was missing in asterisk.rb file before host and port number.
